---
- hosts: apache
  become: yes

  pre_tasks:
    - name: Update apt
      become: yes
      apt: 
        cache_valid_time: 1800
        update_cache: yes

  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest

    - name: restart server
      service: name=apache2 state=restarted

  handlers: 
    - name: restart apache2
      service: name=apache2 state=restarted 

