---
- hosts: all
  become: yes
  vars:
    doc_root: /var/www/html

  pre_tasks:
    - name: Update apt
      apt: 
        update_cache: yes

  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest 
           
    - name: create custom document root
      file: path={{ doc_root }} state=directory owner=www-data group=www-data

    - name: set up HTML file
      copy: src=index.html dest={{ doc_root }}  owner=www-data group=www-data mode=0644

    - name: restart apache
      service: name=apache2 state=restarted

  handlers: 
    - name: restart apache2
      service: name=apache2 state=restarted 

