---
- hosts: all
  become: yes

  pre_tasks:
    - name: Update apt
      apt: 
        update_cache: yes

  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest 

    - name: start apache2
      service: name=apache2 state=started 

      ##need to build out adding items to groups before calling rolling restart per group

    - name: rolling restart per group
      # service: name=group state=restarted
      # with_items: groups.webservers

    - name: check status
      command: service apache2 status
      changed_when: false


  handlers: 
    - name: restart apache
      service: name=apache state=restarted 

    

