---
- hosts: all
  become: yes

  pre_tasks:
    - name: Update apt
      apt: 
        update_cache: yes

  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest 

    - name: start apache2
      service: name=apache2 state=started 

      ##need to build out adding services to groups before calling rolling restart per group

    - name: adding services to groups
      service: 
        name: group1
      with_items:
        - apache
        - gearman

    - name: rolling restart per group
      service: 
        name: group1
        state: restarted

    - name: check status
      command: service apache2 status
      changed_when: false


  handlers: 
    - name: restart apache
      service: name=apache state=restarted 

    

